# Generated by Django 6.0.6 on 2026-06-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Контакты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'app_contactrequest',
            },
        ),
        migrations.CreateModel(
            name='Продвижение',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='promotion/')),
            ],
            options={
                'verbose_name': 'Продвижение',
                'verbose_name_plural': 'Продвижения',
                'db_table': 'app_promotion',
            },
        ),
        migrations.CreateModel(
            name='Услуга',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_short_description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='Услуги/')),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'app_service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='СервисПродвижение',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.продвижение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Продвижение', to='app.услуга')),
            ],
            options={
                'verbose_name': 'СервисПродолжение',
                'verbose_name_plural': 'СервисПродолжения',
                'db_table': 'app_servicepromotion',
            },
        ),
        migrations.CreateModel(
            name='СвязанныеУслуги',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.услуга')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Связанные_услуги', to='app.услуга')),
            ],
            options={
                'verbose_name': 'СвязаннаяУслуга',
                'verbose_name_plural': 'СвязанныеУслуги',
                'db_table': 'app_relatedservice',
            },
        ),
        migrations.CreateModel(
            name='Отзыв',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='отзывы/videos/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='отзывы/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='отзывы', to='app.услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'app_review',
            },
        ),
        migrations.CreateModel(
            name='Врач',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Врачи/')),
                ('description', models.TextField()),
                ('service', models.ManyToManyField(related_name='Врачи', to='app.услуга')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'db_table': 'app_doctor',
            },
        ),
        migrations.CreateModel(
            name='ЦенаУслуги',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Цены', to='app.услуга')),
            ],
            options={
                'verbose_name': 'ЦенаУслуги',
                'verbose_name_plural': 'ЦенаУслуг',
                'db_table': 'app_serviceprice',
            },
        ),
    ]
